AllCops:
  RunRailsCops: true
Metrics/LineLength:
  Max: 119
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20
Metrics/BlockNesting:
  Max: 5
Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: true
Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Style/EmptyLinesAroundBlockBody:
  Enabled: false
