db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=asdasd123123

web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/bitubi
  volumes_from:
    - bundle
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    - DEV_DB_NAME=bitubi_development
    - DEV_DB_USERNAME=root
    - DEV_DB_PASSWORD=asdasd123123

bundle:
  # 'image' will vary depending on your docker-compose
  # project name. You may need to run `docker-compose build web`
  # before this works.
  image: bitubi_web
  command: echo 'haha'
  volumes:
    - /bundle
